# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hidedot < Formula
  desc "A dotfiles manager written in Go"
  homepage "https://github.com/youhide/hideDot"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/youhide/hideDot/releases/download/v0.0.3/hideDot_Darwin_x86_64.tar.gz"
      sha256 "4c0d9321cdb1b1e7197c187f414bb163353d7bec12f925ce11238c5cdeec97d5"

      def install
        bin.install "hidedot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/youhide/hideDot/releases/download/v0.0.3/hideDot_Darwin_arm64.tar.gz"
      sha256 "3a15f683df84ef2bf891e85e872c91d1b0a5360e048ee410b12d64496d1b9198"

      def install
        bin.install "hidedot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/youhide/hideDot/releases/download/v0.0.3/hideDot_Linux_x86_64.tar.gz"
        sha256 "2200ae51a677598c5b1b7a5b355be2c0fc065b387c30633c558bb0c3bca79efc"

        def install
          bin.install "hidedot"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/youhide/hideDot/releases/download/v0.0.3/hideDot_Linux_arm64.tar.gz"
        sha256 "ba27fe55471da8b47464392e93075ba4afaf8f9796138d972046d167cf531d43"

        def install
          bin.install "hidedot"
        end
      end
    end
  end

  test do
    system "#{bin}/hidedot --help"
  end
end
