# This file was generated by GoReleaser. DO NOT EDIT.
cask "hidedot" do
  version "0.0.6"

  on_macos do
    on_intel do
      sha256 "6b2fd2ed529ed2f4355a4865d8fe24584ee79d567bb5cc693218c16f292e85bf"
      url "https://github.com/youhide/hideDot/releases/download/v#{version}/hideDot_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "54dccf9ed318f43267f12f3e303b1cf3ea468e38f02e723acf33d59eff2902ae"
      url "https://github.com/youhide/hideDot/releases/download/v#{version}/hideDot_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ed7fc77742323ad0a928e5a9d0f4c8e54b60086e3b1c4f9f1bfb328b487f0ad1"
      url "https://github.com/youhide/hideDot/releases/download/v#{version}/hideDot_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "48d968e2bf05e51c64c50d525ad03205f336a3025e750742204e07490d3ab93b"
      url "https://github.com/youhide/hideDot/releases/download/v#{version}/hideDot_Linux_arm64.tar.gz"
    end
  end

  name "hidedot"
  desc "A dotfiles manager written in Go"
  homepage "https://github.com/youhide/hideDot"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hidedot"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hidedot"]
    end
  end

  # No zap stanza required

end
