# This file was generated by GoReleaser. DO NOT EDIT.
cask "hidetop" do
  version "0.0.6"

  on_macos do
    on_intel do
      sha256 "ca250c0086dd144687588e9c7e0356fe4fa283ad13c9eac54ef7825eb7202f69"
      url "https://github.com/youhide/hideTop/releases/download/v#{version}/hideTop_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "bcadc08aaad69d5f026e9aa175b42bd7e8d7fe5edbd2140d1eb58c702364fc29"
      url "https://github.com/youhide/hideTop/releases/download/v#{version}/hideTop_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "510ee3aa8783adeebba57ddc469ae81e97724e47478f34596753cdc09b646c6e"
      url "https://github.com/youhide/hideTop/releases/download/v#{version}/hideTop_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "c3e9917288e66af61992e6c8a7e181540c482360b35684f9022bf01a2818e9e4"
      url "https://github.com/youhide/hideTop/releases/download/v#{version}/hideTop_Linux_arm64.tar.gz"
    end
  end

  name "hidetop"
  desc "A modern terminal-based system monitor written in Go, offering real-time CPU, memory, Apple Silicon GPU metrics, energy impact, and an interactive process list."
  homepage "https://github.com/youhide/hideTop"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hidetop"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hidetop"]
    end
  end

  # No zap stanza required

end
