# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hidedot < Formula
  desc "A dotfiles manager written in Go"
  homepage "https://github.com/youhide/hideDot"
  version "0.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/youhide/hideDot/releases/download/v0.0.5/hideDot_Darwin_x86_64.tar.gz"
      sha256 "c7150383092a81d70aff65e62ed944dc64c049ef542e8d46cc810cf18e0acf37"

      def install
        bin.install "hideDot" => "hidedot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/youhide/hideDot/releases/download/v0.0.5/hideDot_Darwin_arm64.tar.gz"
      sha256 "4b992902709e8d7ccd8d24655f458e0f910aa20716b17e8aa767b9297d46e2ba"

      def install
        bin.install "hideDot" => "hidedot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/youhide/hideDot/releases/download/v0.0.5/hideDot_Linux_x86_64.tar.gz"
      sha256 "2325f34d5568538d7741a2a8971eb4194cb28a681135b15274df880c8873eace"
      def install
        bin.install "hideDot" => "hidedot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/youhide/hideDot/releases/download/v0.0.5/hideDot_Linux_arm64.tar.gz"
      sha256 "d6c4e4b7a91aa925ffb99657cafa8385e88b14abf0fc021253a19959752e7e57"
      def install
        bin.install "hideDot" => "hidedot"
      end
    end
  end

  test do
    system "#{bin}/hidedot --help"
  end
end
