# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hidedot < Formula
  desc "A dotfiles manager written in Go"
  homepage "https://github.com/youhide/hideDot"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/youhide/hideDot/releases/download/v0.0.3/hideDot_Darwin_x86_64.tar.gz"
      sha256 "3e746bb78d0ec5b4752be420d130a08ad7e532471f012d1a416d4853542d51ea"

      def install
        bin.install "hidedot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/youhide/hideDot/releases/download/v0.0.3/hideDot_Darwin_arm64.tar.gz"
      sha256 "5493197dfece2a2c8d9161fcbdb6659f89ffd7422155f25303a7dc0d422a9b18"

      def install
        bin.install "hidedot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/youhide/hideDot/releases/download/v0.0.3/hideDot_Linux_x86_64.tar.gz"
        sha256 "be1c9c52b0c038d01b1cbc7b04cce33c29ae5c74bfd3d51edd61e6d0135e5a40"

        def install
          bin.install "hidedot"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/youhide/hideDot/releases/download/v0.0.3/hideDot_Linux_arm64.tar.gz"
        sha256 "8faa563524e218d6c2b00348ffd4376c3ae049fddbd7afa55b6154b28fdb9b43"

        def install
          bin.install "hidedot"
        end
      end
    end
  end

  test do
    system "#{bin}/hidedot --help"
  end
end
